// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNGV_q_toXxBX_oLeSJUexSEfZTTGz4s',
    appId: '1:363352659444:web:f8d8f27477d13d225055a1',
    messagingSenderId: '363352659444',
    projectId: 'conexao-saude-1ac50',
    authDomain: 'conexao-saude-1ac50.firebaseapp.com',
    storageBucket: 'conexao-saude-1ac50.firebasestorage.app',
    measurementId: 'G-D4YP2HFLP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMaJb7ZasrSyJKSZR5LVpC9bqrdAODPk',
    appId: '1:363352659444:android:39b26928af1aac075055a1',
    messagingSenderId: '363352659444',
    projectId: 'conexao-saude-1ac50',
    storageBucket: 'conexao-saude-1ac50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCL6nFSiv-eIDouQ1XW8S1joZmMSlAZqs',
    appId: '1:363352659444:ios:740748719cefff1a5055a1',
    messagingSenderId: '363352659444',
    projectId: 'conexao-saude-1ac50',
    storageBucket: 'conexao-saude-1ac50.firebasestorage.app',
    iosBundleId: 'com.example.conexaoSaude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCL6nFSiv-eIDouQ1XW8S1joZmMSlAZqs',
    appId: '1:363352659444:ios:740748719cefff1a5055a1',
    messagingSenderId: '363352659444',
    projectId: 'conexao-saude-1ac50',
    storageBucket: 'conexao-saude-1ac50.firebasestorage.app',
    iosBundleId: 'com.example.conexaoSaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNGV_q_toXxBX_oLeSJUexSEfZTTGz4s',
    appId: '1:363352659444:web:e90c9dfbb41fbdb85055a1',
    messagingSenderId: '363352659444',
    projectId: 'conexao-saude-1ac50',
    authDomain: 'conexao-saude-1ac50.firebaseapp.com',
    storageBucket: 'conexao-saude-1ac50.firebasestorage.app',
    measurementId: 'G-SDRN0ZVD30',
  );

}